spring.application.name=LiterLuana
spring.datasource.url=jdbc:postgresql://localhost:5432/liter_alura_db
spring.datasource.username=LuanaA
spring.datasource.password=130519
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true